### ISSUE TITLE
Major issue with EluLib, CableManager ..

### ISSUE THREAD

**Issue by hAmpzter** [End-of-Days-Modpack-Team/Synthesis#13]
We have had an enormous TPS-lag (as bad as to that the server died a couple of times) with the following error:
java.lang.Error
	at java.util.AbstractCollection.toArray(Unknown Source)
	at elucent.elulib.tile.CableManager.onWorldTick(CableManager.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1202_CableManager_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Full crash report:**
[crash-2018-01-14_20.50.43-server.txt](https://github.com/End-of-Days-Modpack-Team/Synthesis/files/1629888/crash-2018-01-14_20.50.43-server.txt)

**Our solution**
We removed the following mods and went from _server dying_ and _topping at 2.02 TPS_ to **20 TPS** and **stable**:
elulib-0.1.11
blockcraftery-0.13
gadgetrycore-0.1.1
gadgetrymachines-0.1.2
gadgetrytransmission-0.1.1

**Comment by hAmpzter** [comment]
We are no longer running this server and I don't think that the issue is not relevant anymore. Closing!
